name: Integration with Compatibility
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test-opensearch:
    env:
      TEST_OPENSEARCH_SERVER: http://localhost:9250
      PORT: 9250
    strategy:
      fail-fast: false
      matrix:
        cluster-version: [ "1.0.0", "1.3.1", "2.0.0", "2.1.0", "2.2.0", "2.3.0", "2.4.0" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increase system limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - uses: ./.github/actions/opensearch
        with:
          cluster-version: ${{ matrix.cluster-version }}
          disable-security: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Build and test with Rake
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          ruby -v
          bundle install
          rake test:integration
