name: Draft Release

on:
  push:
    tags:
      - "*"

jobs:
  dry_release:
    env:
      GEM_PRIVATE_KEY: .github/dummy.gem-private_key.pem
      GEM_PUBLIC_CERT: .github/dummy.gem-public_cert.pem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler: none
      - name: Determine Ruby Version
        run: |
          set -x
          min_ruby_version=$(ruby -e 'puts Gem::Specification.load("opensearch-aws-sigv4.gemspec").required_ruby_version.to_s.match(/\d+\.\d+/)[0]')
          echo "RUBY_VERSION=$min_ruby_version" >> $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler: latest
      - name: Build and Install Gem
        run: |
          gem build opensearch-aws-sigv4.gemspec
          gem cert --add $GEM_PUBLIC_CERT
          gem install opensearch-aws-sigv4-*.gem
          gem uninstall opensearch-aws-sigv4 -x
          gem install opensearch-aws-sigv4-*.gem -P MediumSecurity
          gem uninstall opensearch-aws-sigv4 -x
          gem install opensearch-aws-sigv4-*.gem -P HighSecurity

  draft_release:
    needs: dry_release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - id: get_approvers
        run: |
          echo "approvers=$(cat .github/CODEOWNERS | grep @ | tr -d '* ' | sed 's/@/,/g' | sed 's/,//1')" >> $GITHUB_OUTPUT
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ steps.get_approvers.outputs.approvers }}
          minimum-approvals: 1
          issue-title: "Release ${{ github.ref_name }}"
          issue-body: "Please approve or deny the release **TAG**: ${{ github.ref_name }}  **COMMIT**: ${{ github.sha }}. 
          The release pipeline for this gem can be found at https://build.ci.opensearch.org/blue/organizations/jenkins/release-opensearch-ruby-aws-sigv4/activity"
          exclude-workflow-initiator-as-approver: true
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GET_SECRET_IAM_ROLE }}
          aws-region: us-east-1
      - name: Download signing key
        run: |
          aws secretsmanager get-secret-value --secret-id jenkins-opensearchproject-rubygems-private-key --query SecretString --output text > gem-private_key.pem
      - name: Build and package gem artifact
        run: |
          gem build opensearch-aws-sigv4.gemspec
          mkdir dist && mv *.gem dist/
          tar -cvf artifacts.tar.gz dist
      - name: Draft a release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            artifacts.tar.gz
